[package]
name = "frankenstein"
version = "0.1.0"
authors = ["Ayrat Badykov <ayratin555@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = "2.0"
multipart = "0.17"
mime_guess = "2.0"

[dev-dependencies]
httpmock = "0.5.7"