[package]
name = "frankenstein"
version = "0.1.0"
authors = ["Ayrat Badykov <ayratin555@gmail.com>"]
edition = "2018"
description = "frankenstein is in active development. it's published to take the name on crates.io"
license = "WTFPL"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "1.5"
[dependencies.reqwest]
version = "^0.11"
default-features = false
features = ["json", "multipart"]

[dev-dependencies]
